steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - pack
      - build
      - gcr.io/shcm-app-1/github.com/greghammahgerg/playbill_maker:$COMMIT_SHA
      - --builder
      - gcr.io/buildpacks/builder

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/shcm-app-1/github.com/greghammahgerg/playbill_maker:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - playbill-maker
      - --image=gcr.io/shcm-app-1/github.com/greghammahgerg/playbill_maker:$COMMIT_SHA
      - --region=us-east1

options:
  logging: CLOUD_LOGGING_ONLY